import {testOrders} from './fixtures.mjs';
import {test,expect} from '@playwright/test';
import {todayKey} from '../public/core.mjs';
import {readFile} from 'node:fs/promises';
const devConfig=await readFile('.dev.vars','utf8');
const password=JSON.parse(devConfig.match(/^APP_PASSWORD=(".*")$/m)[1]);
function orderData(extra={}){return {id:crypto.randomUUID(),customer:'საცდელი კლიენტი',product:'საცდელი პროდუქტი',priceCents:8550,region:'თბილისი',address:'წერეთლის გამზირი 24, ბინა 8',phone:'555 12 34 56',shipDate:todayKey(),deliveryTime:'14:00–18:00',notes:'მისვლამდე დაურეკეთ.',...extra}}
test('desktop and mobile reference layouts, expansion, search, empty state, install UI',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));const orders=testOrders(todayKey());await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;const data=path==='/api/config'?{ready:true,pushReady:false}:path==='/api/session'?{authenticated:true}:path==='/api/orders'?{orders}:{};await route.fulfill({json:data})});await page.setViewportSize({width:1440,height:1000});await page.goto('/');await expect(page.locator('.order-card')).toHaveCount(7);await expect(page.locator('#today-message')).toContainText('3 შეკვეთა');await page.screenshot({path:'preview-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'preview-mobile.png',fullPage:false});await page.locator('[data-order="test-0"]').click();await expect(page.locator('#details-test-0')).toBeVisible();await expect(page.locator('#details-test-0')).toContainText('წერეთლის გამზირი 24, ბინა 8');await page.screenshot({path:'preview-expanded.png',fullPage:false});
  await page.locator('[data-action="search"]').click();await page.locator('#search').fill('ნინო');await expect(page.locator('.order-card')).toHaveCount(1);await page.locator('#search').fill('არარსებული');await expect(page.locator('.empty-state')).toContainText('შეკვეთა ვერ მოიძებნა');await page.locator('#search').fill('');await page.locator('[data-filter="sent"]').click();await expect(page.locator('.order-card')).toHaveCount(1);await page.locator('.mobile-settings').click();await expect(page.locator('#settings-dialog')).toBeVisible();await expect(page.locator('#settings-content')).toContainText('შეკვეთები ინახება დაცულ საცავში');await page.locator('#settings-dialog [data-close]').click();
  for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)}await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.style.fontSize='32px');await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('real create, reload, edit, send, restore, delete persists in D1',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#login-dialog')).toBeVisible();await page.locator('#password').fill(password);await page.locator('#login-form button').click();await expect(page.locator('#login-dialog')).not.toBeVisible();await expect(page.locator('#orders')).toHaveAttribute('aria-busy','false');await page.locator('[data-action="new"]:visible').first().click();
  const name='ტესტი '+Date.now();await page.getByLabel('სახელი და გვარი',{exact:true}).fill(name);await page.getByLabel('პროდუქტი',{exact:true}).fill('თეთრეულის ნაკრები');await page.getByLabel('ფასი (₾)',{exact:true}).fill('85,50');await page.getByLabel('ქალაქი / რეგიონი',{exact:true}).fill('თბილისი');await page.getByLabel('ზუსტი მისამართი',{exact:true}).fill('წერეთლის გამზირი 24, ბინა 8');await page.getByLabel('ტელეფონის ნომერი',{exact:true}).fill('555 12 34 56');await page.getByLabel('მიტანის დრო',{exact:false}).fill('14:00–18:00');await page.getByLabel('დამატებითი ინფორმაცია',{exact:false}).fill('მისვლამდე დაურეკეთ.');await page.locator('#save-button').click();await expect(page.locator('#order-dialog')).not.toBeVisible();
  let card=page.locator('.order-card').filter({hasText:name});await expect(card).toContainText('85,5');await page.reload();card=page.locator('.order-card').filter({hasText:name});await expect(card).toBeVisible();await card.locator('.order-summary').click();await expect(card.locator('a[href="tel:555123456"]')).toBeVisible();await card.locator('[data-edit]').click();await page.getByLabel('დამატებითი ინფორმაცია',{exact:false}).fill('რედაქტირებული <img src=x onerror=alert(1)>');await page.locator('#save-button').click();await expect(card).toContainText('რედაქტირებული <img');await expect(card.locator('img')).toHaveCount(0);await card.locator('[data-status]').click();await page.locator('[data-filter="sent"]').click();await expect(page.locator('.order-card').filter({hasText:name})).toBeVisible();await page.reload();card=page.locator('.order-card').filter({hasText:name});await page.locator('[data-filter="sent"]').click();await card.locator('.order-summary').click();await card.locator('[data-status]').click();await page.locator('[data-filter="all"]').click();await card.locator('.order-summary').click();await card.locator('[data-delete]').click();await expect(page.locator('#confirm-dialog')).toBeVisible();await page.locator('#confirm-delete').click();await expect(card).toHaveCount(0);await page.reload();await expect(card).toHaveCount(0);expect(errors).toEqual([]);
});
test('auth, validation, idempotent retry and version conflict do not corrupt records',async({request})=>{
  expect((await request.get('/api/orders')).status()).toBe(401);expect((await request.post('/api/login',{data:{password:'incorrect'}})).status()).toBe(401);expect((await request.post('/api/login',{data:{password},headers:{Origin:'https://foreign.example'}})).status()).toBe(403);expect((await request.post('/api/login',{data:{password}})).ok()).toBe(true);const data=orderData();
  expect((await request.post('/api/orders',{data:{...data,phone:'5'}})).status()).toBe(400);const created=await request.post('/api/orders',{data});expect(created.status()).toBe(201);const duplicate=await request.post('/api/orders',{data});expect((await duplicate.json()).order.id).toBe(data.id);const edit=await request.put('/api/orders/'+data.id,{data:{...data,notes:'new',version:1}});expect((await edit.json()).order.version).toBe(2);expect((await request.put('/api/orders/'+data.id,{data:{...data,notes:'stale',version:1}})).status()).toBe(409);const list=(await(await request.get('/api/orders')).json()).orders;expect(list.find(o=>o.id===data.id).notes).toBe('new');expect(list.filter(o=>o.id===data.id)).toHaveLength(1);expect((await request.delete('/api/orders/'+data.id,{data:{version:2}})).ok()).toBe(true);
});
test('first login is remembered after closing and reopening; a new device still needs the code',async({browser})=>{
  const first=await browser.newContext();
  const page=await first.newPage();await page.goto('http://127.0.0.1:8791/');await expect(page.locator('#login-dialog')).toBeVisible();await page.locator('#password').fill(password);await page.locator('#login-form button').click();await expect(page.locator('#login-dialog')).not.toBeVisible();await expect(page.locator('#orders')).toHaveAttribute('aria-busy','false');
  const saved=await first.storageState(),remembered=saved.cookies.find(cookie=>cookie.name==='orders_session');expect(remembered.httpOnly).toBe(true);expect(remembered.expires).toBeGreaterThan(Date.now()/1000+390*86400);await first.close();
  const reopened=await browser.newContext({storageState:saved});const reopenedPage=await reopened.newPage();await reopenedPage.goto('http://127.0.0.1:8791/');await expect(reopenedPage.locator('#orders')).toHaveAttribute('aria-busy','false');await expect(reopenedPage.locator('#login-dialog')).not.toBeVisible();
  const session=await reopened.request.get('http://127.0.0.1:8791/api/session');expect((await session.json()).authenticated).toBe(true);expect(session.headers()['set-cookie']).toContain('Max-Age=34560000');
  await reopened.request.post('http://127.0.0.1:8791/api/logout',{data:{}});expect((await reopened.request.get('http://127.0.0.1:8791/api/orders')).status()).toBe(401);await reopened.close();
  const fresh=await browser.newContext();const freshPage=await fresh.newPage();await freshPage.goto('http://127.0.0.1:8791/');await expect(freshPage.locator('#login-dialog')).toBeVisible();await fresh.close();
});
test('connection failure keeps form values and allows retry',async({page,context})=>{
  await page.request.post('/api/login',{data:{password}});await page.goto('/');await expect(page.locator('.empty-state')).toBeVisible();
  await page.locator('[data-action="new"]:visible').first().click();const name='კავშირის ტესტი '+Date.now();await page.locator('#f-customer').fill(name);await page.locator('#f-product').fill('სუფრა');await page.locator('#f-price').fill('60');await page.locator('#f-region').fill('აჭარა');await page.locator('#f-address').fill('ქუჩა 1');await page.locator('#f-phone').fill('555123456');await context.setOffline(true);await page.locator('#save-button').click();await expect(page.locator('#form-error')).toBeVisible();await expect(page.locator('#f-customer')).toHaveValue(name);await expect(page.locator('#order-dialog')).toBeVisible();await context.setOffline(false);await page.locator('#save-button').click();await expect(page.locator('#order-dialog')).not.toBeVisible();const record=(await(await page.request.get('/api/orders')).json()).orders.find(o=>o.customer===name);await page.request.delete('/api/orders/'+record.id,{data:{version:record.version}});
});

test('old sample URL requires sign-in and shows only saved orders',async({page})=>{await page.goto('/?demo=1');await expect(page.locator('#login-dialog')).toBeVisible();await expect(page.locator('.order-card')).toHaveCount(0);await page.locator('#password').fill(password);await page.locator('#login-form button').click();await expect(page.locator('#login-dialog')).not.toBeVisible();await expect(page.locator('#orders')).toHaveAttribute('aria-busy','false');const saved=await page.request.get('/api/orders');const {orders}=await saved.json();await expect(page.locator('.order-card')).toHaveCount(orders.filter(o=>o.status==='pending').length);await expect(page.locator('#demo-badge')).toHaveCount(0)});
