import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createECDH,webcrypto} from 'node:crypto';
import {buildPushPayload} from '@block65/webcrypto-web-push';
import {todayKey,dayDifference,orderGroups,parsePrice,validateOrder,validDate,demoOrders,georgianDate,money} from '../public/core.mjs';
import {validateSubscription,sendDailyReminders} from '../server/worker.mjs';
test('Georgian calendar changes at Tbilisi midnight and noon is 08:00 UTC',()=>{assert.equal(todayKey(new Date('2026-10-08T19:59:59Z')),'2026-10-08');assert.equal(todayKey(new Date('2026-10-08T20:00:00Z')),'2026-10-09');assert.equal(todayKey(new Date('2026-10-09T08:00:00Z')),'2026-10-09');assert.equal(dayDifference('2026-11-01','2026-10-31'),1)});
test('dates stay Georgian without relying on browser locale support',()=>{assert.equal(georgianDate('2026-10-09',{weekday:true}),'9 ოქტომბერი · პარასკევი');assert.equal(georgianDate('2026-10-09',{year:true}),'9 ოქტომბერი 2026');assert.equal(money(8550),'85,50 ₾')});
test('today first, remaining pending newest first, sent excluded',()=>{const orders=demoOrders('2026-10-09');orders.push({...orders[3],id:'overdue',shipDate:'2026-10-08',createdAt:Date.now()+1000});const groups=orderGroups(orders,'all','','2026-10-09');assert.equal(groups[0].key,'today');assert.equal(groups[0].items.length,3);assert.equal(groups[1].items[0].id,'overdue');assert.ok(groups.flatMap(g=>g.items).every(o=>o.status==='pending'));assert.equal(orderGroups(orders,'sent','','2026-10-09')[0].items.length,1);assert.equal(orderGroups(orders,'all','ნინო','2026-10-09')[0].items[0].customer,'ნინო ბერიძე')});
test('money keeps cents and validates date and phone',()=>{assert.equal(parsePrice('85,50'),8550);assert.equal(parsePrice('0'),0);assert.throws(()=>parsePrice('1.001'));assert.throws(()=>parsePrice('-5'));assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2028-02-29'),true);const order=demoOrders('2026-10-09')[0];assert.equal(validateOrder(order).priceCents,8500);assert.throws(()=>validateOrder({...order,phone:'555'}));assert.throws(()=>validateOrder({...order,priceCents:85.5}))});
test('subscriptions reject private destinations and wrong encryption keys',()=>{const client=createECDH('prime256v1');client.generateKeys();const sub={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:client.getPublicKey().toString('base64url'),auth:Buffer.alloc(16,2).toString('base64url')}};assert.equal(validateSubscription(sub).endpoint,sub.endpoint);assert.throws(()=>validateSubscription({...sub,endpoint:'https://127.0.0.1/private'}));assert.throws(()=>validateSubscription({...sub,endpoint:'https://fcm.googleapis.com.evil.example/send'}));assert.throws(()=>validateSubscription({...sub,keys:{...sub.keys,auth:'abc'}}))});
test('push library creates Apple-compatible encrypted aes128gcm payload',async()=>{const client=createECDH('prime256v1');client.generateKeys();const server=createECDH('prime256v1');server.generateKeys();const payload=await buildPushPayload({data:JSON.stringify({title:'დღევანდელი შეკვეთები',body:'დღეს 3 შეკვეთა გაქვს გასაგზავნი.'}),options:{ttl:14400}},{endpoint:'https://web.push.apple.com/test',keys:{p256dh:client.getPublicKey().toString('base64url'),auth:Buffer.alloc(16,3).toString('base64url')}},{subject:'mailto:test@example.com',publicKey:server.getPublicKey().toString('base64url'),privateKey:server.getPrivateKey().toString('base64url')});assert.equal(new Headers(payload.headers).get('Content-Encoding'),'aes128gcm');assert.ok(new Headers(payload.headers).get('Authorization').startsWith('vapid '));assert.ok(payload.body.byteLength>100)});
function mockDB(count,rows){const operations=[];return {operations,prepare(sql){return {bind(...values){operations.push({sql,values});return this},async first(){return {total:count}},async all(){return {results:rows}},async run(){operations.push({sql});return {meta:{changes:1}}}}}}}
test('no daily message when nothing is due; successful messages deduplicated and expired removed',async()=>{const empty=mockDB(0,[]);let calls=0;const env={DB:empty,VAPID_PUBLIC_KEY:'key',VAPID_PRIVATE_KEY:'key',VAPID_SUBJECT:'mailto:test@example.com'};const result=await sendDailyReminders(env,Date.parse('2026-10-09T08:00:00Z'),async()=>{calls++;return 201});assert.equal(result.reason,'no-orders');assert.equal(calls,0);const db=mockDB(2,[{endpoint:'ok',subscription:'{"endpoint":"ok"}'},{endpoint:'expired',subscription:'{"endpoint":"expired"}'}]);const messages=[];const active=await sendDailyReminders({...env,DB:db},Date.parse('2026-10-09T08:00:00Z'),async(_env,sub,message)=>{messages.push(message);return sub.endpoint==='ok'?201:410});assert.equal(active.sent,1);assert.ok(messages.every(m=>m.body.includes('2 შეკვეთა')));assert.ok(db.operations.some(o=>o.sql.startsWith('UPDATE push_subscriptions')&&o.values?.[0]==='2026-10-09'));assert.ok(db.operations.some(o=>o.sql.startsWith('DELETE FROM push_subscriptions')))});
